site_name: 我的博客
nav:
    - 主页: index.md
    - spring:
        - 'spring/1、Spring IOC 中的注解.md'
        - 'spring/2、Spring中的动态代理.md'
        - 'spring/3、Spring AOP.md'
        - 'spring/4、Spring 事务.md'
        - 'spring/5、本次Spring教程中涉及的相关依赖.md'
    - Spring教程: SpringIOC.md
    - 关于: about.md
# theme: readthedocs
